### ISSUE TITLE
ReflectionProperty::getDeclaringClass doesn't work with traits

### ISSUE THREAD

**Issue by enumag** [Kdyby/Autowired#17] opened 2015-01-04 13:41 UTC
I tried to write a trait with its own dependencies and for laziness I used the `@autowire` annotation in that trait. Turns out it only works with fully-qualified `@var` annotation but not with use statements.

The reason is that if the property was declared in a trait, `ReflectionProperty::getDeclaringClass()` returns the class that uses the trait, not the trait itself. Because of that the use statements are read from wrong file.

More information about the topic as well as possible solution is here: http://mouf-php.com/blog/php_reflection_api_traits

Should I send a PR using the solution from the article above or are you against such solution?

**Comment by enumag** [comment] 2015-01-04 13:44
Maybe it would be better to have a helper function in Nette\Reflection for this. I'm not sure though because it seems that Nette\Reflection might soon be deprecated.

**Comment by enumag** [comment] 2015-01-04 13:53
Sure enough, `@inject` annotations in Nette\DI are affeced as well.

**Comment by fprochazka** [comment] 2015-01-04 14:38
AFAIK the logic is from nette\reflection, kdyby\autowired is not expanding the uses by itself. So the bugreport should be filled there.

**Comment by enumag** [comment] 2015-01-04 14:46
Actually that's not completely true because Kdyby\Autowired calls `Nette\Reflection\AnnotationsParser::expandClassName` which expects an annotation value and a class reflection. You pass the wrong class reflection.

https://github.com/Kdyby/Autowired/blob/9278842c5167402c15da2f092c9d88fefa15d97f/src/Kdyby/Autowired/AutowireProperties.php#L201

**Comment by fprochazka** [comment] 2015-01-04 14:57
So the problem is that the `getDeclaringClass` doesn't return reflection fo trait? Well, that seems like a bug pf php to me. But okey, do you know how to fix it? Can you please send a pullrq? :)

**Comment by enumag** [comment] 2015-01-04 15:01
I'll try to add a static helper for this into Nette\Reflection first. ;-)

**Comment by fprochazka** [comment] 2015-01-04 15:02
Good idea :)

**Comment by enumag** [comment] 2015-01-04 22:00
@fprochazka The reflection PR is merged, I'll send a PR for this when the commit appears in stable nette.

**Comment by fprochazka** [comment] 2015-01-04 22:29
Thank you :)

**Comment by fprochazka** [comment] 2015-05-09 21:02
Fixed by https://github.com/Kdyby/Autowired/pull/18 ?

**Closed by fprochazka** 2015-05-09 21:02 UTC

**Comment by enumag** [comment] 2015-05-09 21:16
Yes, fixed. Forgot to close this one.
